import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  ActivityIndicator, Alert, RefreshControl, Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as Location from 'expo-location';
import { WebView } from 'react-native-webview';
import { colors, spacing, radius } from '../theme';
import { useAuth } from '../context/AuthContext';
import { getSubscription, putSubscription } from '../util/db';
import { supabase } from '../util/supabase';
import QRScannerModal from '../components/QRScannerModal';

// ─── helpers ─────────────────────────────────────────────────────────────────

function todayKey() {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm   = String(d.getMonth() + 1).padStart(2, '0');
  const dd   = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function toDateKey(val) {
  if (!val) return '';
  if (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}/.test(val)) return val.slice(0, 10);
  const d = new Date(val);
  if (!Number.isNaN(d.getTime())) {
    return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  }
  return String(val).slice(0, 10);
}

// Normalize a raw record (web schema: clockIn/clockOut/notes, or legacy
// mobile schema: checkIn/checkOut/check_in/...) into one shape the screen uses.
function normalizeRecord(r) {
  return {
    id:         r.id         ?? null,
    employeeId: r.employeeId ?? r.employee_id ?? r.empId ?? r.emp_id ?? '',
    date:       r.date       ?? r.attendanceDate ?? r.attendance_date ?? r.day ?? '',
    checkIn:    r.clockIn    ?? r.checkIn    ?? r.check_in  ?? r.timeIn  ?? r.time_in  ?? null,
    checkOut:   r.clockOut   ?? r.checkOut   ?? r.check_out ?? r.timeOut ?? r.time_out ?? null,
    status:     (r.status ?? '').toString().toLowerCase(),
    hours:      r.hours      ?? r.hoursWorked ?? r.hours_worked ?? null,
    location:   r.location   ?? r.checkInLocation ?? null,
    notes:      r.notes      ?? '',
  };
}

/** "HH:MM" 24h from a Date object */
function toHHMM(date) {
  return `${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;
}

/** "HH:MM" → "08:00 AM" */
function fmtTime(val) {
  if (!val) return '--';
  const m = String(val).match(/^(\d{1,2}):(\d{2})/);
  if (!m) return val;
  const h = parseInt(m[1], 10);
  const ampm = h >= 12 ? 'PM' : 'AM';
  const h12  = String(h % 12 || 12).padStart(2, '0');
  return `${h12}:${m[2]} ${ampm}`;
}

/** Compute hours between two "HH:MM" strings */
function hoursBetween(checkIn, checkOut) {
  if (!checkIn || !checkOut) return 0;
  const rx = /^(\d{1,2}):(\d{2})$/;
  const a  = String(checkIn).match(rx);
  const b  = String(checkOut).match(rx);
  if (a && b) {
    const diff = (parseInt(b[1],10)*60+parseInt(b[2],10)) - (parseInt(a[1],10)*60+parseInt(a[2],10));
    return diff > 0 ? diff/60 : 0;
  }
  return 0;
}

/**
 * Determine attendance status from a "HH:MM" check-in time, using the same
 * rule as the web app's AttendancePage: compare against the employee's
 * assigned shift start + the subscription's settings.lateThreshold (minutes).
 */
function deriveStatus(checkIn, shiftStart = '09:00', lateThresholdMin = 15) {
  if (!checkIn) return 'absent';
  const m = String(checkIn).match(/^(\d{1,2}):(\d{2})/);
  if (!m) return 'present';
  const clockMins = parseInt(m[1], 10) * 60 + parseInt(m[2], 10);

  const sm = String(shiftStart).match(/^(\d{1,2}):(\d{2})/);
  const shiftMins = sm ? parseInt(sm[1], 10) * 60 + parseInt(sm[2], 10) : 9 * 60;

  return clockMins <= shiftMins + Number(lateThresholdMin || 0) ? 'present' : 'late';
}

/**
 * Parse and validate a QR payload string from the web Shift Manager.
 *
 * Expected JSON shape:
 *   {
 *     type:           "attendance_qr",
 *     subscriptionId: string,
 *     shiftId:        number | string,
 *     issuedAt:       ISO string,
 *     permanent:      boolean,         // true = never expires, print-once QR
 *     date?:          "YYYY-MM-DD",    // only present for daily QR codes
 *     expiresAt?:     ISO string,      // only present for daily QR codes
 *   }
 *
 * Returns { ok: true, payload } or { ok: false, error: string }
 */
function parseQRPayload(raw) {
  try {
    const payload = JSON.parse(raw);

    if (payload.type !== 'attendance_qr') {
      return { ok: false, error: 'This QR code is not an attendance QR. Please use the one generated by your shift manager.' };
    }
    if (!payload.subscriptionId) {
      return { ok: false, error: 'Invalid QR code: missing workspace information.' };
    }

    // Permanent QR codes (print-once, posted on the wall) skip the
    // date/expiry checks entirely — they're valid every day, forever.
    if (payload.permanent === true) {
      return { ok: true, payload };
    }

    if (!payload.date) {
      return { ok: false, error: 'Invalid QR code: missing date information.' };
    }

    // Check if QR is for today
    const qrDate  = payload.date?.slice(0, 10);
    const today   = todayKey();
    if (qrDate !== today) {
      return { ok: false, error: `This QR code is for ${qrDate}, not today (${today}). Please ask your shift manager for today's QR code.` };
    }

    // Check expiry if present
    if (payload.expiresAt) {
      const expires = new Date(payload.expiresAt);
      if (!isNaN(expires.getTime()) && expires < new Date()) {
        return { ok: false, error: 'This QR code has expired. Please ask your shift manager for a new one.' };
      }
    }

    return { ok: true, payload };
  } catch {
    return { ok: false, error: 'Could not read QR code. Make sure you are scanning an AttendMS attendance QR code.' };
  }
}

const STATUS_COLORS = { present: colors.present, late: colors.late, absent: colors.absent };
const STATUS_LABELS = { present: 'Present', late: 'Late', absent: 'Absent' };
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

/**
 * Builds a self-contained HTML page that renders a Leaflet map with
 * OpenStreetMap tiles — no API key, no billing account, no Google Cloud
 * setup required. Shows a marker + 100m radius circle at the given coords,
 * the same visual the previous react-native-maps screen showed.
 */
function buildLeafletMapHTML(latitude, longitude, label) {
  const safeLabel = (label || 'Your Location').replace(/[<>&"]/g, '');
  return `
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
  <style>
    html, body, #map { height: 100%; margin: 0; padding: 0; }
    .leaflet-control-attribution { font-size: 9px; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
  <script>
    const lat = ${latitude};
    const lng = ${longitude};
    const map = L.map('map', { zoomControl: false, attributionControl: true }).setView([lat, lng], 17);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '© OpenStreetMap contributors'
    }).addTo(map);
    L.marker([lat, lng]).addTo(map).bindPopup(${JSON.stringify(safeLabel)});
    L.circle([lat, lng], {
      radius: 100,
      color: 'rgba(124,58,237,0.4)',
      fillColor: 'rgba(124,58,237,0.1)',
      fillOpacity: 1,
      weight: 1
    }).addTo(map);
  </script>
</body>
</html>`;
}

// ─── component ────────────────────────────────────────────────────────────────

export default function AttendanceScreen() {
  const { account, subscription, setSubscription } = useAuth();
  const [tab, setTab]                   = useState('today');
  const [loading, setLoading]           = useState(true);
  const [refreshing, setRefreshing]     = useState(false);
  const [submitting, setSubmitting]     = useState(false);
  const [todayRecord, setTodayRecord]   = useState(null);
  const [allRecords, setAllRecords]     = useState([]);
  const [location, setLocation]         = useState(null);
  const [locationAddr, setLocationAddr] = useState('');
  const [locationErr, setLocationErr]   = useState('');
  const [locLoading, setLocLoading]     = useState(false);
  const [listMonth, setListMonth]       = useState(new Date().getMonth());
  const [listYear]                      = useState(new Date().getFullYear());
  const [showScanner, setShowScanner]   = useState(false);   // ← QR scanner modal
  const mapRef = useRef(null);

  const subscriptionId = account?.subscriptionId ?? null;
  const employeeId     = account?.employeeId     ?? null;

  const employees     = subscription?.enrolledEmployees ?? [];
  const shifts        = subscription?.shifts ?? [];
  const lateThreshold = Number(subscription?.settings?.lateThreshold ?? 15);
  const myEmployee    = employees.find(e => String(e.id) === String(employeeId));
  const myShift       = myEmployee?.shiftId
    ? shifts.find(s => String(s.id) === String(myEmployee.shiftId))
    : null;
  const shiftStart    = myShift?.start ?? '09:00';
  // 'onsite' shifts require QR scan; 'remote' (default) shifts use GPS
  const clockInMode   = myShift?.clockInMode ?? 'remote';
  const isOnsite      = clockInMode === 'onsite';

  // ── fetch data ─────────────────────────────────────────────────────────────
  const fetchData = useCallback(async () => {
    if (!subscriptionId || !employeeId) { setLoading(false); return; }
    try {
      const sub = await getSubscription(subscriptionId);
      if (!sub) return;
      const records = (sub.attendanceRecords ?? [])
        .map(normalizeRecord)
        .filter(r => String(r.employeeId).trim() === String(employeeId).trim());

      const tKey = todayKey();
      const todayRec = records.find(r => toDateKey(r.date) === tKey) ?? null;

      setAllRecords(records);
      setTodayRecord(todayRec);
    } catch (err) {
      console.warn('[Attendance] fetch error:', err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [subscriptionId, employeeId]);

  useEffect(() => { fetchData(); }, [fetchData, refreshing]);

  const onRefresh = useCallback(() => setRefreshing(true), []);

  // ── request location ───────────────────────────────────────────────────────
  const requestLocation = useCallback(async () => {
    setLocLoading(true);
    setLocationErr('');
    try {
      const { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== 'granted') {
        setLocationErr('Location permission denied. Please enable it in Settings.');
        setLocLoading(false);
        return;
      }
      const pos = await Location.getCurrentPositionAsync({
        accuracy: Location.Accuracy.High,
      });
      const { latitude, longitude } = pos.coords;
      setLocation({ latitude, longitude });

      const [geo] = await Location.reverseGeocodeAsync({ latitude, longitude });
      if (geo) {
        const parts = [geo.name, geo.street, geo.city, geo.region].filter(Boolean);
        setLocationAddr(parts.join(', '));
      }
    } catch (err) {
      setLocationErr('Could not get location. Please try again.');
    } finally {
      setLocLoading(false);
    }
  }, []);

  useEffect(() => {
    if (tab === 'today' && !location && !isOnsite) requestLocation();
  }, [tab, isOnsite]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── core clock-in/out logic (shared by both manual and QR paths) ───────────
  const clockIn = useCallback(async ({ timeStr, dateStr, locStr, locOverride = false }) => {
    const sub = await getSubscription(subscriptionId);
    if (!sub) throw new Error('Failed to load subscription data.');

    const records = sub.attendanceRecords ?? [];
    const status  = deriveStatus(timeStr, shiftStart, lateThreshold);

    const newRecord = {
      id:         `att_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      employeeId: String(employeeId),
      date:       dateStr,
      clockIn:    timeStr,
      clockOut:   null,
      status,
      notes:      locOverride ? 'QR scan clock-in' : '',
      hours:      null,
      location:   locStr,
    };

    const updatedRecords = [...records, newRecord];
    const updatedSub     = { ...sub, attendanceRecords: updatedRecords };

    await putSubscription(updatedSub);
    setSubscription(updatedSub);
    setTodayRecord(normalizeRecord(newRecord));
    setAllRecords(prev => [...prev, normalizeRecord(newRecord)]);

    return { status, timeStr, locStr };
  }, [subscriptionId, employeeId, shiftStart, lateThreshold, setSubscription]);

  const clockOut = useCallback(async ({ timeStr, dateStr }) => {
    const sub = await getSubscription(subscriptionId);
    if (!sub) throw new Error('Failed to load subscription data.');

    const records = sub.attendanceRecords ?? [];
    const hours   = hoursBetween(todayRecord.checkIn, timeStr);

    const updatedRecord = { ...todayRecord, checkOut: timeStr, hours: parseFloat(hours.toFixed(2)) };

    const updatedRecords = records.map(r => {
      const norm = normalizeRecord(r);
      if (
        String(norm.employeeId).trim() === String(employeeId).trim() &&
        toDateKey(norm.date) === dateStr
      ) {
        return { ...r, clockOut: timeStr, hours: parseFloat(hours.toFixed(2)) };
      }
      return r;
    });

    const updatedSub = { ...sub, attendanceRecords: updatedRecords };
    await putSubscription(updatedSub);
    setSubscription(updatedSub);
    setTodayRecord(normalizeRecord(updatedRecord));
    setAllRecords(prev => prev.map(r =>
      toDateKey(r.date) === dateStr && String(r.employeeId).trim() === String(employeeId).trim()
        ? normalizeRecord(updatedRecord) : r
    ));

    return { hours };
  }, [subscriptionId, employeeId, todayRecord, setSubscription]);

  // ── manual clock in / out button ───────────────────────────────────────────
  const handleClockAction = useCallback(async () => {
    if (!subscriptionId || !employeeId) {
      Alert.alert('Error', 'Session expired. Please log in again.');
      return;
    }
    if (!location) {
      Alert.alert('Location Required', 'We need your location to record attendance. Tap "Use My Location" to allow it.');
      return;
    }

    const now     = new Date();
    const timeStr = toHHMM(now);
    const dateStr = todayKey();
    const locStr  = locationAddr || `${location.latitude.toFixed(5)}, ${location.longitude.toFixed(5)}`;

    setSubmitting(true);
    try {
      if (!todayRecord) {
        const { status } = await clockIn({ timeStr, dateStr, locStr });
        Alert.alert('Checked In ✓', `Time: ${fmtTime(timeStr)}\nStatus: ${STATUS_LABELS[status]}\nLocation: ${locStr}`);
      } else if (!todayRecord.checkOut) {
        const { hours } = await clockOut({ timeStr, dateStr });
        Alert.alert('Checked Out ✓', `Time: ${fmtTime(timeStr)}\nHours worked: ${hours.toFixed(2)} hrs`);
      } else {
        Alert.alert('Already Recorded', 'You have already checked in and out for today.');
      }
    } catch (err) {
      Alert.alert('Error', err.message ?? 'Something went wrong.');
    } finally {
      setSubmitting(false);
    }
  }, [subscriptionId, employeeId, location, locationAddr, todayRecord, clockIn, clockOut]);

  // ── QR scan handler ────────────────────────────────────────────────────────
  const handleQRScanned = useCallback(async (rawData) => {
    if (!subscriptionId || !employeeId) {
      Alert.alert('Error', 'Session expired. Please log in again.');
      return;
    }

    // 1. Parse & validate the QR payload
    const { ok, payload, error } = parseQRPayload(rawData);
    if (!ok) {
      Alert.alert('Invalid QR Code', error);
      return;
    }

    // 2. Confirm the QR belongs to this employee's workspace
    if (payload.subscriptionId !== subscriptionId) {
      Alert.alert(
        'Wrong Workspace',
        'This QR code belongs to a different company. Please scan the QR code issued by your shift manager.',
      );
      return;
    }

    // 3. Confirm the QR shift matches the employee's assigned shift
    if (myEmployee?.shiftId && payload.shiftId && String(payload.shiftId) !== String(myEmployee.shiftId)) {
      Alert.alert(
        'Wrong Shift QR',
        `This QR code is for a different shift. Please scan the QR for your assigned shift (${myShift?.name ?? 'your shift'}).`,
      );
      return;
    }

    // 4. Guard: already clocked in and out
    if (todayRecord?.checkIn && todayRecord?.checkOut) {
      Alert.alert('Already Recorded', 'You have already checked in and out for today.');
      return;
    }

    const now     = new Date();
    const timeStr = toHHMM(now);
    const dateStr = todayKey();
    // Onsite employees don't fetch GPS — the QR scan itself is the proof of presence.
    const locStr  = locationAddr || (location
      ? `${location.latitude.toFixed(5)}, ${location.longitude.toFixed(5)}`
      : 'Onsite (QR verified)');

    setSubmitting(true);
    try {
      if (!todayRecord) {
        // ── QR Clock In ────────────────────────────────────────────────────
        const { status } = await clockIn({ timeStr, dateStr, locStr, locOverride: true });
        Alert.alert(
          'QR Check-In ✓',
          `Time: ${fmtTime(timeStr)}\nStatus: ${STATUS_LABELS[status]}\nShift QR verified ✓`,
        );
      } else if (!todayRecord.checkOut) {
        // ── QR Clock Out ───────────────────────────────────────────────────
        const { hours } = await clockOut({ timeStr, dateStr });
        Alert.alert(
          'QR Check-Out ✓',
          `Time: ${fmtTime(timeStr)}\nHours worked: ${hours.toFixed(2)} hrs\nShift QR verified ✓`,
        );
      }
    } catch (err) {
      Alert.alert('Error', err.message ?? 'Something went wrong.');
    } finally {
      setSubmitting(false);
    }
  }, [subscriptionId, employeeId, location, locationAddr, todayRecord, clockIn, clockOut]);

  // ── derived list for the selected month ────────────────────────────────────
  const prefix = `${listYear}-${String(listMonth+1).padStart(2,'0')}`;
  const listRecords = allRecords
    .filter(r => toDateKey(r.date).startsWith(prefix))
    .sort((a, b) => toDateKey(b.date).localeCompare(toDateKey(a.date)));

  // ── button state ───────────────────────────────────────────────────────────
  const alreadyDone = !!(todayRecord?.checkIn && todayRecord?.checkOut);
  const checkedIn   = !!(todayRecord?.checkIn && !todayRecord?.checkOut);
  const btnColor    = alreadyDone ? colors.textMuted : checkedIn ? colors.absent : colors.present;
  const btnLabel    = alreadyDone ? 'Done' : checkedIn ? 'Check Out' : 'Check In';
  const btnIcon     = alreadyDone ? 'checkmark-circle-outline' : 'finger-print-outline';

  const todayLabel = new Date().toLocaleDateString('en-PH', {
    month: 'long', day: 'numeric', year: 'numeric',
  });

  function formatRecordDate(dateStr) {
    const d = new Date(dateStr + 'T00:00:00');
    return {
      day:  d.toLocaleDateString('en-US', { weekday: 'short' }),
      date: d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    };
  }

  if (loading) {
    return (
      <SafeAreaView style={[styles.safe, styles.center]}>
        <ActivityIndicator size="large" color={colors.primary} />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      {/* ── QR Scanner Modal ── */}
      <QRScannerModal
        visible={showScanner}
        onClose={() => setShowScanner(false)}
        onScanned={handleQRScanned}
      />

      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Attendance</Text>
        <View style={styles.tabRow}>
          <TouchableOpacity
            style={[styles.tabBtn, tab === 'today' && styles.tabActive]}
            onPress={() => setTab('today')}
          >
            <Text style={[styles.tabText, tab === 'today' && styles.tabTextActive]}>
              Today's Attendance
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.tabBtn, tab === 'list' && styles.tabActive]}
            onPress={() => setTab('list')}
          >
            <Text style={[styles.tabText, tab === 'list' && styles.tabTextActive]}>
              Attendance List
            </Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.primary} />}
      >
        {/* ── TODAY TAB ────────────────────────────────────────────────── */}
        {tab === 'today' ? (
          <View style={styles.body}>
            <Text style={styles.date}>{todayLabel}</Text>

            {/* Time Card */}
            <View style={styles.timeCard}>
              <Text style={styles.timeLabel}>
                {!todayRecord ? 'Not Yet Checked In' : alreadyDone ? 'Attendance Complete' : 'Checked In'}
              </Text>

              {todayRecord?.checkIn ? (
                <View style={styles.checkTimesRow}>
                  <View style={styles.checkItem}>
                    <Ionicons name="log-in-outline" size={14} color={colors.present} />
                    <Text style={styles.checkItemLabel}>In</Text>
                    <Text style={styles.checkItemValue}>{fmtTime(todayRecord.checkIn)}</Text>
                  </View>
                  {todayRecord?.checkOut && (
                    <View style={styles.checkItem}>
                      <Ionicons name="log-out-outline" size={14} color={colors.absent} />
                      <Text style={styles.checkItemLabel}>Out</Text>
                      <Text style={styles.checkItemValue}>{fmtTime(todayRecord.checkOut)}</Text>
                    </View>
                  )}
                </View>
              ) : (
                <View style={styles.clockRow}>
                  <Text style={styles.clockNum}>--</Text>
                  <Text style={styles.clockColon}>:</Text>
                  <Text style={styles.clockNum}>--</Text>
                </View>
              )}

              {todayRecord?.location ? (
                <View style={styles.locationRow}>
                  <Ionicons name="location-outline" size={13} color={colors.textMuted} />
                  <Text style={styles.locationText}>{todayRecord.location}</Text>
                </View>
              ) : null}

              {todayRecord && (
                <View style={[styles.statusBadge, { backgroundColor: (STATUS_COLORS[todayRecord.status] ?? colors.textMuted) + '20' }]}>
                  <Text style={[styles.statusBadgeText, { color: STATUS_COLORS[todayRecord.status] ?? colors.textMuted }]}>
                    {STATUS_LABELS[todayRecord.status] ?? todayRecord.status}
                  </Text>
                </View>
              )}
            </View>

            {/* Map — remote employees only; onsite employees rely on QR scan, no GPS needed */}
            {!isOnsite && (location ? (
              <View style={styles.mapContainer}>
                <WebView
                  ref={mapRef}
                  style={styles.map}
                  originWhitelist={['*']}
                  source={{ html: buildLeafletMapHTML(location.latitude, location.longitude, locationAddr) }}
                  scrollEnabled={false}
                  javaScriptEnabled
                  domStorageEnabled
                />

                <View style={styles.mapOverlay}>
                  <Ionicons name="location" size={12} color={colors.purple} />
                  <Text style={styles.mapOverlayText} numberOfLines={1}>
                    {locationAddr || `${location.latitude.toFixed(5)}, ${location.longitude.toFixed(5)}`}
                  </Text>
                </View>
              </View>
            ) : (
              <View style={styles.mapPlaceholder}>
                {locLoading ? (
                  <>
                    <ActivityIndicator color={colors.purple} />
                    <Text style={styles.mapPlaceholderText}>Getting your location…</Text>
                  </>
                ) : (
                  <>
                    <Ionicons name="map-outline" size={36} color={colors.textMuted} />
                    <Text style={styles.mapPlaceholderText}>
                      {locationErr || 'Location not available'}
                    </Text>
                    <TouchableOpacity style={styles.locationBtn} onPress={requestLocation}>
                      <Ionicons name="locate-outline" size={14} color={colors.white} />
                      <Text style={styles.locationBtnText}>Use My Location</Text>
                    </TouchableOpacity>
                  </>
                )}
              </View>
            ))}

            {!isOnsite && locationErr && location ? (
              <Text style={styles.locErrText}>{locationErr}</Text>
            ) : null}

            {/* ── Clock In / Out buttons — mode-aware ── */}
            <View style={styles.checkInWrapper}>

              {isOnsite ? (
                /* ── ONSITE: primary action is QR scan ── */
                <>
                  {!alreadyDone && (
                    <TouchableOpacity
                      style={[styles.checkInBtn, {
                        backgroundColor: alreadyDone ? colors.textMuted : checkedIn ? colors.absent : colors.purple,
                        shadowColor: checkedIn ? colors.absent : colors.purple,
                      }]}
                      onPress={() => setShowScanner(true)}
                      disabled={submitting || alreadyDone}
                      activeOpacity={0.8}
                    >
                      {submitting
                        ? <ActivityIndicator color={colors.white} />
                        : <Ionicons name="qr-code-outline" size={26} color={colors.white} />
                      }
                      <Text style={styles.checkInText}>{checkedIn ? 'Scan Out' : 'Scan QR'}</Text>
                    </TouchableOpacity>
                  )}

                  {alreadyDone && (
                    <TouchableOpacity
                      style={[styles.checkInBtn, { backgroundColor: colors.textMuted, shadowColor: colors.textMuted }]}
                      disabled
                      activeOpacity={0.8}
                    >
                      <Ionicons name="checkmark-circle-outline" size={28} color={colors.white} />
                      <Text style={styles.checkInText}>Done</Text>
                    </TouchableOpacity>
                  )}

                  <View style={styles.modeTag}>
                    <Ionicons name="qr-code-outline" size={11} color={colors.purple} />
                    <Text style={styles.modeTagText}>Onsite · QR scan required</Text>
                  </View>
                </>
              ) : (
                /* ── REMOTE: primary action is GPS fingerprint ── */
                <>
                  <TouchableOpacity
                    style={[styles.checkInBtn, { backgroundColor: btnColor, shadowColor: btnColor }]}
                    onPress={handleClockAction}
                    disabled={submitting || alreadyDone}
                    activeOpacity={0.8}
                  >
                    {submitting
                      ? <ActivityIndicator color={colors.white} />
                      : <Ionicons name={btnIcon} size={28} color={colors.white} />
                    }
                    <Text style={styles.checkInText}>{btnLabel}</Text>
                  </TouchableOpacity>

                  <View style={styles.modeTag}>
                    <Ionicons name="location-outline" size={11} color={colors.present} />
                    <Text style={[styles.modeTagText, { color: colors.present }]}>Remote · GPS location</Text>
                  </View>

                  {!location && !locLoading && (
                    <TouchableOpacity style={styles.retryLocBtn} onPress={requestLocation}>
                      <Ionicons name="locate-outline" size={14} color={colors.purple} />
                      <Text style={styles.retryLocText}>Refresh Location</Text>
                    </TouchableOpacity>
                  )}
                </>
              )}
            </View>
          </View>
        ) : (
          /* ── LIST TAB ──────────────────────────────────────────────────── */
          <View style={styles.listBody}>
            {/* Month selector */}
            <View style={styles.listMonthRow}>
              <TouchableOpacity
                style={styles.monthArrow}
                onPress={() => setListMonth(m => m === 0 ? 11 : m - 1)}
              >
                <Ionicons name="chevron-back" size={16} color={colors.textSecondary} />
              </TouchableOpacity>
              <Text style={styles.monthText}>{MONTHS[listMonth]} {listYear}</Text>
              <TouchableOpacity
                style={styles.monthArrow}
                onPress={() => setListMonth(m => m === 11 ? 0 : m + 1)}
              >
                <Ionicons name="chevron-forward" size={16} color={colors.textSecondary} />
              </TouchableOpacity>
            </View>

            {/* Summary strip */}
            {listRecords.length > 0 && (
              <View style={styles.summaryRow}>
                {['present','late','absent'].map(s => (
                  <View key={s} style={styles.summaryItem}>
                    <Text style={[styles.summaryNum, { color: STATUS_COLORS[s] }]}>
                      {listRecords.filter(r => r.status === s).length}
                    </Text>
                    <Text style={styles.summaryLabel}>{STATUS_LABELS[s]}</Text>
                  </View>
                ))}
              </View>
            )}

            {listRecords.length === 0 ? (
              <View style={styles.emptyState}>
                <Ionicons name="calendar-outline" size={40} color={colors.textMuted} />
                <Text style={styles.emptyText}>No attendance records for {MONTHS[listMonth]} {listYear}</Text>
              </View>
            ) : (
              listRecords.map((item, i) => {
                const { day, date } = formatRecordDate(item.date);
                return (
                  <View key={item.id ?? i} style={styles.listItem}>
                    <View style={styles.listDate}>
                      <Text style={styles.listDay}>{day}</Text>
                      <Text style={styles.listDateText}>{date}</Text>
                    </View>
                    <View style={styles.listTimes}>
                      <View style={styles.listTimeRow}>
                        <Ionicons name="log-in-outline" size={13} color={colors.present} />
                        <Text style={styles.listTimeText}>{fmtTime(item.checkIn) || '--'}</Text>
                      </View>
                      <View style={styles.listTimeRow}>
                        <Ionicons name="log-out-outline" size={13} color={colors.absent} />
                        <Text style={styles.listTimeText}>{fmtTime(item.checkOut) || '--'}</Text>
                      </View>
                    </View>
                    <View style={[styles.statusBadge, { backgroundColor: (STATUS_COLORS[item.status] ?? colors.textMuted) + '20' }]}>
                      <Text style={[styles.statusText, { color: STATUS_COLORS[item.status] ?? colors.textMuted }]}>
                        {STATUS_LABELS[item.status] ?? item.status}
                      </Text>
                    </View>
                  </View>
                );
              })
            )}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe:   { flex: 1, backgroundColor: colors.cream },
  scroll: { flex: 1 },
  center: { justifyContent: 'center', alignItems: 'center' },

  // Header / tabs
  header: {
    backgroundColor: colors.white,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    alignItems: 'center',
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: colors.text, marginBottom: spacing.md },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: colors.cream,
    borderRadius: radius.full,
    padding: 3,
  },
  tabBtn:         { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: radius.full },
  tabActive:      { backgroundColor: colors.primary },
  tabText:        { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  tabTextActive:  { color: colors.white, fontWeight: '700' },

  // Today body
  body: { padding: spacing.xl },
  date: { fontSize: 14, color: colors.textSecondary, marginBottom: spacing.md },

  // Time card
  timeCard: {
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    marginBottom: spacing.md,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06, shadowRadius: 8, elevation: 3,
  },
  timeLabel:        { color: colors.textMuted, fontSize: 12, marginBottom: spacing.sm },
  clockRow:         { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.sm },
  clockNum:         { fontSize: 40, fontWeight: '800', color: colors.text, letterSpacing: 2 },
  clockColon:       { fontSize: 40, fontWeight: '800', color: colors.text, marginHorizontal: 2 },
  checkTimesRow:    { flexDirection: 'row', gap: spacing.xl, marginBottom: spacing.sm },
  checkItem:        { flexDirection: 'row', alignItems: 'center', gap: 4 },
  checkItemLabel:   { fontSize: 12, color: colors.textMuted },
  checkItemValue:   { fontSize: 13, fontWeight: '700', color: colors.text },
  locationRow:      { flexDirection: 'row', alignItems: 'flex-start', marginBottom: spacing.sm },
  locationText:     { fontSize: 11, color: colors.textMuted, marginLeft: 4, width: '85%' },
  statusBadge:      { paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: radius.sm, marginTop: spacing.xs },
  statusBadgeText:  { fontSize: 12, fontWeight: '700' },

  // Map
  mapContainer: {
    height: 320,
    borderRadius: radius.lg,
    overflow: 'hidden',
    marginBottom: spacing.xl,
    position: 'relative',
  },
  map: { width: '100%', height: '100%' },
  mapOverlay: {
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    backgroundColor: 'rgba(255,255,255,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    gap: 4,
  },
  mapOverlayText: { fontSize: 11, color: colors.textSecondary, flex: 1 },

  mapPlaceholder: {
    height: 200,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
    gap: spacing.sm,
  },
  mapPlaceholderText: { fontSize: 13, color: colors.textMuted, textAlign: 'center', paddingHorizontal: spacing.xl },
  locationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.purple,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    gap: 6,
    marginTop: spacing.xs,
  },
  locationBtnText: { fontSize: 12, color: colors.white, fontWeight: '600' },
  locErrText:      { fontSize: 11, color: colors.absent, textAlign: 'center', marginBottom: spacing.md },

  // Check in / QR buttons area
  checkInWrapper: { alignItems: 'center', marginBottom: spacing.xl, gap: spacing.sm },
  checkInBtn: {
    width: 90, height: 90, borderRadius: 45,
    justifyContent: 'center', alignItems: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4, shadowRadius: 12, elevation: 8,
  },
  checkInText:   { color: colors.white, fontSize: 10, fontWeight: '700', marginTop: 4 },

  // "or" divider
  orRow: { flexDirection: 'row', alignItems: 'center', width: '60%', gap: spacing.sm, marginVertical: 2 },
  orLine: { flex: 1, height: 1, backgroundColor: colors.border },
  orText: { fontSize: 11, color: colors.textMuted, fontWeight: '500' },

  // QR scan button
  qrBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    paddingVertical: 12,
    borderRadius: radius.full,
    borderWidth: 1.5,
    borderColor: colors.purple,
    backgroundColor: colors.purple + '0D',
  },
  qrBtnText: { fontSize: 13, fontWeight: '700', color: colors.purple },

  retryLocBtn:   { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: spacing.xs },
  modeTag: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: spacing.sm, paddingVertical: 4,
    borderRadius: radius.full,
    backgroundColor: colors.purple + '12',
  },
  modeTagText: { fontSize: 10, fontWeight: '600', color: colors.purple },
  retryLocText:  { fontSize: 12, color: colors.purple, fontWeight: '500' },

  // Attendance List
  listBody: { padding: spacing.xl },
  listMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  monthArrow: { padding: 6 },
  monthText:  { fontSize: 15, fontWeight: '700', color: colors.text, minWidth: 90, textAlign: 'center' },

  summaryRow: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  summaryItem:  { flex: 1, alignItems: 'center' },
  summaryNum:   { fontSize: 22, fontWeight: '800' },
  summaryLabel: { fontSize: 11, color: colors.textMuted, marginTop: 2 },

  emptyState: { alignItems: 'center', paddingVertical: spacing.xxl * 2, gap: spacing.sm },
  emptyText:  { fontSize: 13, color: colors.textMuted, textAlign: 'center' },

  listItem: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  listDate:     { width: 80 },
  listDay:      { fontSize: 13, fontWeight: '700', color: colors.text },
  listDateText: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  listTimes:    { flex: 1, gap: 4 },
  listTimeRow:  { flexDirection: 'row', alignItems: 'center', gap: 4 },
  listTimeText: { fontSize: 12, color: colors.textSecondary },
  statusText:   { fontSize: 11, fontWeight: '700' },
});